name: CI - Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build -t ciutkarshcd/backend:latest ./backend
          docker push ciutkarshcd/backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t ciutkarshcd/frontend:latest ./frontend
          docker push ciutkarshcd/frontend:latest
